### ISSUE TITLE
explore handling different shapes using function pointers?

### ISSUE THREAD

**Issue by yxqd** [mcvine/McVineGPU#8]
If we can use function pointers, then we may be able to implement the dynamic dispatching needed for the composite pattern and the visitor pattern to support constructive solid geometry.

https://stackoverflow.com/questions/15644261/cuda-function-pointers

**Comment by ilumsden** [comment]
In CUDA, function pointers cause large slow downs because they block the inlining that nvcc does automatically. Instead of using function pointers, a key value will be passed into the general `intersect` kernel to choose the correct algorithm via a `switch` statement.
